# .github/workflows/build.yml
name: Node Build.

on: [push]

#on:
#    [push, pull_request]
#on:
#    pull_request:
#        branches:
#            - develop
#on:
#    schedule:
#        - cron: '0 8-17 * * 1-5'
##Minute (0 - 59)
##Hour (0 - 23)
##Day of the month (1 - 31)
##Month (1 - 12)
##Day of the week (0 - 6)



jobs:
    mainbuild:
#        runs-on: ${{ matrix.os }}
        runs-on: ubuntu-latest
     
    strategy:
        matrix:
            node-version: [12.x]
            os: [ubuntu-latest]
         
    steps:

    - uses: actions/checkout
    - name: Run node.js on latest Windows.
      uses: actions/setup-node
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM and build.
      run: |
        npm ci
        npm run build
